### ISSUE TITLE
Wer macht mit?

### ISSUE THREAD

**Issue by btemperli** [cevi/event-overview-cevidb#1]
Wer hilft mit?

- @btemperli 

Wer hat Interesse am Output?

- Cevi Schweiz

(Ihr dürft gerne ergänzen...)

**Comment by carlobeltrame** [comment]
Falls ihr das als generell einsetzbares Tool umsetzen möchtet, das neben dem Cevi Schweiz auch Ortsgruppen für ihre eigenen Anlassübersichten verwenden können, könnte es sich lohnen auf hitobito/hitobito#1687 aufzusetzen. Die Kalender sind genau als solche vorgefilterte Anlass-Listen gedacht. So könnte ein Teil der ansonsten nötigen Code-Kenntnisse durchs UI in hitobito abgedeckt werden.
Die Kalender-Anlässe können derzeit noch nicht via Service Token abgerufen werden, die Kurse können noch nicht nach Kurs-Typ (z.B. nur J+S-Kurse) gefiltert werden, und Layer-übergreifende Kalender sind auch noch nicht möglich. Ich könnte mir da vorstellen, auf Seite hitobito etwas mitzuhelfen.

**Comment by wp99cp** [comment]
@btemperli kannst du mir Admin Rechte auf diesem Repo geben? Damit ich die GitHub Action einrichten kann?

**Comment by btemperli** [comment]
@wp99cp Danke für deinen Einsatz! Ist erledigt.
