### ISSUE TITLE
Kalender-Feeds oder Events API

### ISSUE THREAD

**Issue by wp99cp** [cevi/event-overview-cevidb#2]
Dieses Issue dient der Evaluation, ob wir das Projekt mittels Kalender-Feeds oder der Event API realisieren sollen.

> Falls ihr das als generell einsetzbares Tool umsetzen möchtet, das neben dem Cevi Schweiz auch Ortsgruppen für ihre eigenen Anlassübersichten verwenden können, könnte es sich lohnen auf hitobito/hitobito#1687 aufzusetzen. Die Kalender sind genau als solche vorgefilterte Anlass-Listen gedacht. So könnte ein Teil der ansonsten nötigen Code-Kenntnisse durchs UI in hitobito abgedeckt werden.
> Die Kalender-Anlässe können derzeit noch nicht via Service Token abgerufen werden, die Kurse können noch nicht nach Kurs-Typ (z.B. nur J+S-Kurse) gefiltert werden, und Layer-übergreifende Kalender sind auch noch nicht möglich. Ich könnte mir da vorstellen, auf Seite hitobito etwas mitzuhelfen.

_Originally posted by @carlobeltrame in https://github.com/cevi/event-overview-cevidb/issues/1_

### Vorteile
- Existierendes UI, das es erlaubt visuell die Anlässe/Kurse vorzufiltern
- Neben der Darstellung als Webseite können die Anlässe auch in einem Kalender eingebunden werden

 ### Nachteile
- Backend/Webinterface müssen mit ics Dateien arbeiten, JSON ist da deutlich einfacher Hand zuhaben
- Nicht alle Informationen sind im Kalender sichtbar (z.B. Anmelde-Link, Kurs-Typ, Anzahl Teilnehmer usw)
- Kurse/Lager werden in mehrere Einträge aufgeteilt (Vorweekend, Lagerwoche, ...), diese müssten manuell wieder zusammengesetzt werden

### Vorteile
- Returnt ein JSON-Objekt, einfachere Verarbeitung durch das Backend
- Mittels API-Keys, können queries auf verschiedenen Layern gemacht werden
- für mich intuitiv die richtige API, für was gibt es eine Events API, wenn nicht für eine solche Applikation?

 ### Nachteile
- Filtering zur Zeit nicht wirklich möglich (kann aber implementiert werden)
- Nicht alle Felder sind verfügbar (Mindestalter, ...)

@nchiapol @btemperli @carlobeltrame gerne bin ich offen für eure Meinungen, er kennt euch da z.T. besser aus als ich.

**Comment by btemperli** [comment]
Ich persönlich würde wohl eher in Richtung Event-API, insbesondere für die spätere Implementierung auf eigenen Webseiten (Regionalverbände, Cevi Schweiz).

Betreffend den Feldern können wir uns wohl beim Cevi Alpin orientieren, sie haben bei allen Anlässen die gleiche Beschreibung eingesetzt und lesen einfach diese mit einer einfache Variante aus. Ich denke, das könnten wir auch hinkriegen. Gibt es eine «Tag»-Funktion bei Anlässen? Dann könnte man allenfalls auch damit arbeiten.

Beispiel Cevi Alpin:
https://db.cevi.ch/groups/3030/events/3141
https://cevi-alpin.ch/tour/neujahrslager-2/

**Comment by wp99cp** [comment]
Ja das Taggen von Anlässen/Kursen ist seit neustem möglich. Dies kann sicher verwendet werden.

Damit wir eine nationale Kurs-Übersicht hinkriegen, würde ich so viel wie möglich mit offiziellen Feldern arbeiten und falls nötig neue Felder zu den Anlässen/der API hinzufügen (lassen).

Ich traue unseren regionalen Geschäftsstellen zwar viel zu, denke es ist aber nicht realistisch, dass sich alle für jeden Anlass an ein fixes Format für die Event Beschreibung halten. Die Lösung von Cevi Alpin funktioniert aber soweit ich sehe genau auf diesem Prinzip.

**Comment by carlobeltrame** [comment]
Alle hier genannten Nachteile der Kalender beruhen auf der Tatsache dass man die Events im Kalender noch nicht im JSON-Format abrufen kann. Das wäre aber trivial zu implementieren: Die gefilterte Event-Liste [liegen schon vor](https://github.com/hitobito/hitobito/blob/fe35bfa51f43f6af76178c41e3f6a0d85d4ee1b2/app/controllers/calendars/feeds_controller.rb#L18) und müssten nur noch in einem `format.json` Block durch den ebenfalls bereits bestehenden [event list serializer](https://github.com/hitobito/hitobito/blob/master/app/controllers/events_controller.rb#L181) gejagt werden. Dann kämen genau die gleichen Felder raus wie bei der normalen events API. Damit könnte ich euch aushelfen falls ihr das wollt. Eigentlich wäre es von da au auch gar nicht schwer für euch, beide Arten zu unterstützen, weil sich die Endpoints nur noch in der URL unterscheiden.

Echte sind allerdings die "Nachteile" mit dem Zugangstoken (bei Kalendern kann man kein _one token to rule them all_ machen, sondern das Token ist direkt im Kalender-Link) und mit der fehlenden Fähigkeit für Layer-übergreifende Kalender.

**Comment by btemperli** [comment]
Es braucht so oder so eine möglichst einfach, klare & genaue Anleitung, damit die regionalen und nationalen Geschäftsstellen das einfach umsetzen können.

**Comment by btemperli** [comment]
Wichtig ist insbesondere aus nationaler Sicht, dass Events aus verschiedenen Regionalverbänden und der nationalen Ebene angezeigt werden können. Verstehe ich das richtig, dass das nur via Event-API möglich ist?

**Comment by nchiapol** [comment]
Aus meiner Sicht, sollte hier ganz klar die API genutzt werden. Wie bereits auf anderem Kanal geschrieben haben wir das auch beim Cevi Alpin so gemacht und das hat sich grundsätzlich bewährt. Zudem enthält der Kalender Feed nur ein minimales Set an Daten. 

Zu den Punkten der Diskussion:
  - Ich weiss nicht, welche Felder wir benötigen, aber eigentlich sollte alles in der Event API verfügbar sein. (Das Mindestalter ist an den Kurs-Typ geknüpft und nicht pro Kurs definierbar. Deshalb muss es über diese Beziehung gelesen werden. Um eine die Kurstypen nicht übermässig aufzublasen haben wir bei den Kurstypen des Cevi Alpin kein Mindestalter definiert.)
  - Was aktuell in der API fehlt ist die Kontaktperson. Die wird Übersicht wohl nicht brauchen. Eine Übersicht sollte für die Details auf die öffentliche Seite des jeweiligen Kurses verlinken - und dort sind alle Infos. (Und ich glaube niemand will Kurse nach Kontaktperson filtern ;-)
  - In meinen Augen sollte es für die Übersicht keine besondere Anleitung an die Geschäftsstellen brauchen. Die CeviDB-Gruppe sollte die "Best-Practice" definieren, wie Kurse in der DB erfasst werden - und die Übersicht sollte dann darauf aufbauen. (Da der aktuelle Sprint einiges verändert, werden wir die Best-Practice erst danach aktualisieren, grundsätzlich sehe ich da aber keine Probleme.)
  - Das Dachverbands-Token hat auf alle Kurse Zugriff. (habe ich eben getestet)

**Comment by wp99cp** [comment]
Ich schliesse dieses Issue mit dem Fazit, dass wir die API verwenden werden.
