### ISSUE TITLE
Setup Automatic Deployment

### ISSUE THREAD

**Issue by wp99cp** [cevi/event-overview-cevidb#26]
I saw that you are already builing the images with a GitHub action. That's perfect!

Should I change the config on our docker swarm cluster in order to expose the new application on [kurse.cevi.tools](https://kurse.cevi.tools/). Or should we wait for futher development?

**Comment by patrickuhlmann** [comment]
It was already exposed under events.cevi.tools. I also exposed it unter kurse.cevi.tools. See https://github.com/cevi/cevi-tools-infrastructure/commit/ca06c7d6bbf1a03594cc560d9626923d9d9ac54d
