### ISSUE TITLE
Old Data get Listed

### ISSUE THREAD

**Issue by wp99cp** [cevi/event-overview-cevidb#30]
If you search for something like "Lagerleiter" some old courses get listed

![image](https://github.com/cevi/event-overview-cevidb/assets/34008738/c8842a4f-6c26-4a64-aa0a-fdf6e5128359)

**Comment by patrickuhlmann** [comment]
I haven't yet implemented the daily sync but I updated the start date to today and redeployed so now there are only up-to-date courses. I'll keep the ticket open until the daily sync is implemented tough.

**Comment by patrickuhlmann** [comment]
closed with https://github.com/cevi/event-overview-cevidb/commit/25ffc39ed3b486e26f364860b131d94d12d91d21
