### ISSUE TITLE
Anmeldelink

### ISSUE THREAD

**Issue by wp99cp** [cevi/event-overview-cevidb#6]
- [x] Anmelde-Link für Externe gleich übernehmen (falls möglich, habe den Kurs hier entsprechend angepasst: https://cevi.puzzle.ch/groups/300/events/1179)

_Originally posted by @btemperli in https://github.com/cevi/event-overview-cevidb/issues/3#issuecomment-1384880033_
            
Was meinst du damit? Gibt es da noch einen anderen Link als dieser hier?

![image](https://user-images.githubusercontent.com/34008738/218067725-c890511e-373a-41c5-855e-c40688ef9df4.png)

Das ist der `external_application_link`

**Comment by btemperli** [comment]
Danke, dann passt das so.
Habe ich das richtig im Kopf, dass es auch Anlässe gibt, die keinen `external_application_link` gibt? Wie sieht dieser Fall aus?
Falls das unklar wäre, gerne wieder öffnen, sonst ist das erledigt.

**Comment by btemperli** [comment]
Vorschläge: 

- [ ] Den Link zur Anmeldung in einem neuen Tab öffnen (`a href="" target="_blank"`)
- [ ] Falls der Link für Externe geschlossen ist, den Link ausblenden (Beispiel beim letzten Test-Kurs _Anmeeldung Test IV_ zeigt der [Anmelde-Link](https://cevi.puzzle.ch/groups/6/public_events/1174) auf eine 404-Seite).

**Comment by patrickuhlmann** [comment]
Das Verhalten mit "Anmeldung für externe geschlossen" scheint sich unterdessen geändert zu haben. Habe heute kurz getestet. 

Ist die Anmeldung für externe geöffnet sieht man die Beschreibung etc. des Events auch wenn man nicht in der Cevi.db eingeloggt ist. 

Ist hingegen die Anmeldung für externe geschlossen so führt der Link auch auf die Seite des Events aber es wird ein Loginbildschirm angezeigt. Sobald man sich einloggt kann man die Kursinformationen sehen. 

Aus diesem Grund zeige ich den Link weiterhin an. Ist man eingeloggt funktioniert er direkt, andernfalls muss man sich einloggen und landet dann auf dem entsprechenden Event.
